/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != ''",
    "deleteRule": "@request.auth.id != ''",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3804902632",
        "max": 100,
        "min": 0,
        "name": "nome_empresa",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select1788359516",
        "maxSelect": 1,
        "name": "cidade",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "Alagoinhas",
          "Americana",
          "Amsterdam",
          "Anapolis",
          "Ankara",
          "Aparecida de Goiania",
          "Aracaju",
          "Arapiraca",
          "Araraquara",
          "Araras",
          "Araucaria",
          "Asuncion",
          "Athens",
          "Auckland",
          "Bangkok",
          "Barcelona",
          "Beijing",
          "Belem",
          "Belo Horizonte",
          "Berlin",
          "Boa Vista",
          "Bogota",
          "Botucatu",
          "Brasilia",
          "Brussels",
          "Budapest",
          "Buenos Aires",
          "Cachoeiro de Itapemirim",
          "Cairo",
          "Campina Grande",
          "Campinas",
          "Campo Grande",
          "Campo Largo",
          "Cape Town",
          "Caracas",
          "Caruaru",
          "Cascavel",
          "Caucaia",
          "Caxias do Sul",
          "Chicago",
          "Contagem",
          "Copenhagen",
          "Criciuma",
          "Cuiaba",
          "Curitiba",
          "Delhi",
          "Denver",
          "Diadema",
          "Dubai",
          "Dublin",
          "Duque de Caxias",
          "Eunapolis",
          "Feira de Santana",
          "Florianopolis",
          "Fortaleza",
          "Foz do Iguacu",
          "Franca",
          "Frankfurt",
          "Goiania",
          "Governador Valadares",
          "Guarulhos",
          "Guayaquil",
          "Helsinki",
          "Hong Kong",
          "Houston",
          "Ilheus",
          "Imperatriz",
          "Istanbul",
          "Itabuna",
          "Itajai",
          "Itapetininga",
          "Itaquaquecetuba",
          "Jakarta",
          "Jerusalem",
          "Joao Pessoa",
          "Johannesburg",
          "Joinville",
          "Juazeiro do Norte",
          "Juiz de Fora",
          "Jundiai",
          "Kuala Lumpur",
          "La Paz",
          "Lagos",
          "Lima",
          "Lisbon",
          "London",
          "Londrina",
          "Los Angeles",
          "Luziania",
          "Macapa",
          "Maceio",
          "Madrid",
          "Manaus",
          "Manila",
          "Marilia",
          "Maringa",
          "Maua",
          "Melbourne",
          "Mexico City",
          "Miami",
          "Milan",
          "Mogi Guacu",
          "Mogi das Cruzes",
          "Montes Claros",
          "Montevideo",
          "Montreal",
          "Moscow",
          "Mossoro",
          "Mumbai",
          "Munich",
          "Nairobi",
          "Natal",
          "New York",
          "Niteroi",
          "Nova Friburgo",
          "Nova Iguacu",
          "Novo Hamburgo",
          "Olinda",
          "Osasco",
          "Oslo",
          "Ottawa",
          "Palmas",
          "Panama City",
          "Paramaribo",
          "Parauapebas",
          "Paris",
          "Passo Fundo",
          "Paulista",
          "Petropolis",
          "Piracicaba",
          "Porto Alegre",
          "Porto Velho",
          "Prague",
          "Presidente Prudente",
          "Quito",
          "Recife",
          "Ribeirao Preto",
          "Rio Branco",
          "Rio de Janeiro",
          "Rome",
          "Rondonopolis",
          "Salvador",
          "Santa Maria",
          "Santarem",
          "Santiago",
          "Santo Andre",
          "Santos",
          "Sao Bernardo do Campo",
          "Sao Carlos",
          "Sao Goncalo",
          "Sao Jose do Rio Preto",
          "Sao Jose dos Campos",
          "Sao Luis",
          "Sao Paulo",
          "Sao Vicente",
          "Seattle",
          "Seoul",
          "Singapore",
          "Sorocaba",
          "Stockholm",
          "Sumare",
          "Sydney",
          "Taipei",
          "Taubate",
          "Tehran",
          "Tel Aviv",
          "Teresina",
          "Tokyo",
          "Toronto",
          "Uberaba",
          "Uberlandia",
          "Urucu",
          "Vancouver",
          "Varzea Grande",
          "Vienna",
          "Vitoria",
          "Vitoria da Conquista",
          "Warsaw",
          "Wellington",
          "Zurich"
        ]
      },
      {
        "hidden": false,
        "id": "select2120036095",
        "maxSelect": 1,
        "name": "pais",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CN",
          "CO",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "EC",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GY",
          "HU",
          "ID",
          "IL",
          "IN",
          "IT",
          "JP",
          "KR",
          "MA",
          "MX",
          "MY",
          "NG",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "RU",
          "SA",
          "SE",
          "SG",
          "SR",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VE",
          "VN",
          "ZA"
        ]
      },
      {
        "hidden": false,
        "id": "select1582951535",
        "maxSelect": 1,
        "name": "fuso_horario",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "America/Araguaina",
          "America/Bahia",
          "America/Belem",
          "America/Boa_Vista",
          "America/Campo_Grande",
          "America/Cuiaba",
          "America/Fortaleza",
          "America/Maceio",
          "America/Manaus",
          "America/Noronha",
          "America/Porto_Velho",
          "America/Recife",
          "America/Rio_Branco",
          "America/Santarem",
          "America/Sao_Paulo",
          "America/Argentina/Buenos_Aires",
          "America/Asuncion",
          "America/Bogota",
          "America/Caracas",
          "America/Guayaquil",
          "America/La_Paz",
          "America/Lima",
          "America/Montevideo",
          "America/Paramaribo",
          "America/Santiago",
          "America/Anchorage",
          "America/Chicago",
          "America/Denver",
          "America/Halifax",
          "America/Los_Angeles",
          "America/Mexico_City",
          "America/Montreal",
          "America/New_York",
          "America/Phoenix",
          "America/Toronto",
          "America/Vancouver",
          "Pacific/Honolulu",
          "Europe/Amsterdam",
          "Europe/Athens",
          "Europe/Berlin",
          "Europe/Brussels",
          "Europe/Budapest",
          "Europe/Copenhagen",
          "Europe/Dublin",
          "Europe/Helsinki",
          "Europe/Istanbul",
          "Europe/Lisbon",
          "Europe/London",
          "Europe/Madrid",
          "Europe/Moscow",
          "Europe/Oslo",
          "Europe/Paris",
          "Europe/Prague",
          "Europe/Rome",
          "Europe/Stockholm",
          "Europe/Vienna",
          "Europe/Warsaw",
          "Europe/Zurich",
          "Asia/Bangkok",
          "Asia/Delhi",
          "Asia/Dubai",
          "Asia/Hong_Kong",
          "Asia/Jakarta",
          "Asia/Jerusalem",
          "Asia/Kolkata",
          "Asia/Kuala_Lumpur",
          "Asia/Seoul",
          "Asia/Shanghai",
          "Asia/Singapore",
          "Asia/Taipei",
          "Asia/Tehran",
          "Asia/Tokyo",
          "Australia/Melbourne",
          "Australia/Sydney",
          "Pacific/Auckland",
          "Africa/Cairo",
          "Africa/Johannesburg",
          "Africa/Lagos",
          "Africa/Nairobi",
          "UTC"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1831669462",
        "max": 200,
        "min": 0,
        "name": "weather_api_key",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text928436251",
        "max": 200,
        "min": 0,
        "name": "google_api_key",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text550594806",
        "max": 300,
        "min": 0,
        "name": "google_calendar_id",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "bool699553322",
        "name": "modo_manutencao",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4170278829",
        "max": 500,
        "min": 0,
        "name": "mensagem_manutencao",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "bool782473868",
        "name": "ticker_ativo",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "bool"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1104419137",
        "max": 2000,
        "min": 0,
        "name": "ticker_texto",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      }
    ],
    "id": "pbc_477892449",
    "indexes": [],
    "listRule": "",
    "name": "configuracoes",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.id != ''",
    "viewRule": ""
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_477892449");

  return app.delete(collection);
})
