/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("pbc_477892449")

  // update field
  collection.fields.addAt(2, new Field({
    "hidden": false,
    "id": "select1788359516",
    "maxSelect": 1,
    "name": "cidade",
    "presentable": false,
    "required": false,
    "system": false,
    "type": "select",
    "values": [
      "Alagoinhas",
      "Americana",
      "Amsterdam",
      "Anapolis",
      "Ankara",
      "Aparecida de Goiania",
      "Aracaju",
      "Arapiraca",
      "Araraquara",
      "Araras",
      "Araucaria",
      "Asuncion",
      "Athens",
      "Auckland",
      "Bangkok",
      "Barcelona",
      "Beijing",
      "Belem",
      "Belo Horizonte",
      "Berlin",
      "Boa Vista",
      "Bogota",
      "Botucatu",
      "Brasilia",
      "Brussels",
      "Budapest",
      "Buenos Aires",
      "Cachoeiro de Itapemirim",
      "Cairo",
      "Campina Grande",
      "Campinas",
      "Campo Grande",
      "Campo Largo",
      "Cape Town",
      "Caracas",
      "Caruaru",
      "Cascavel",
      "Caucaia",
      "Caxias do Sul",
      "Chicago",
      "Contagem",
      "Copenhagen",
      "Criciuma",
      "Cuiaba",
      "Curitiba",
      "Delhi",
      "Denver",
      "Diadema",
      "Dubai",
      "Dublin",
      "Duque de Caxias",
      "Eunapolis",
      "Feira de Santana",
      "Florianopolis",
      "Fortaleza",
      "Foz do Iguacu",
      "Franca",
      "Frankfurt",
      "Goiania",
      "Governador Valadares",
      "Guarulhos",
      "Guayaquil",
      "Helsinki",
      "Hong Kong",
      "Houston",
      "Ilheus",
      "Imperatriz",
      "Istanbul",
      "Itabuna",
      "Itajai",
      "Itapetininga",
      "Itaquaquecetuba",
      "Jakarta",
      "Jerusalem",
      "Joao Pessoa",
      "Johannesburg",
      "Joinville",
      "Juazeiro do Norte",
      "Juiz de Fora",
      "Jundiai",
      "Kuala Lumpur",
      "La Paz",
      "Lagos",
      "Lima",
      "Lisbon",
      "London",
      "Londrina",
      "Los Angeles",
      "Luziania",
      "Macapa",
      "Maceio",
      "Madrid",
      "Manaus",
      "Manila",
      "Marilia",
      "Maringa",
      "Maua",
      "Melbourne",
      "Mexico City",
      "Miami",
      "Milan",
      "Mogi Guacu",
      "Mogi das Cruzes",
      "Montes Claros",
      "Montevideo",
      "Montreal",
      "Moscow",
      "Mossoro",
      "Mumbai",
      "Munich",
      "Nairobi",
      "Natal",
      "New York",
      "Niteroi",
      "Nova Friburgo",
      "Nova Iguacu",
      "Novo Hamburgo",
      "Olinda",
      "Osasco",
      "Oslo",
      "Ottawa",
      "Palmas",
      "Panama City",
      "Paramaribo",
      "Parauapebas",
      "Paris",
      "Passo Fundo",
      "Paulista",
      "Petropolis",
      "Piracicaba",
      "Porto Alegre",
      "Porto Velho",
      "Prague",
      "Presidente Prudente",
      "Quito",
      "Recife",
      "Ribeirao Preto",
      "Rio Branco",
      "Rio de Janeiro",
      "Rome",
      "Rondonopolis",
      "Salvador",
      "Santa Maria",
      "Santarem",
      "Santiago",
      "Santo Andre",
      "Santos",
      "Sao Bernardo do Campo",
      "Sao Carlos",
      "Sao Goncalo",
      "Sao Jose do Rio Preto",
      "Sao Jose dos Campos",
      "Sao Luis",
      "Sao Paulo",
      "Sao Vicente",
      "Seattle",
      "Seoul",
      "Singapore",
      "Sorocaba",
      "Stockholm",
      "Sumare",
      "Sydney",
      "Taipei",
      "Taubate",
      "Tehran",
      "Tel Aviv",
      "Teresina",
      "Tokyo",
      "Toronto",
      "Uberaba",
      "Uberlandia",
      "Urucu",
      "Vancouver",
      "Varzea Grande",
      "Vienna",
      "Vitoria",
      "Vitoria da Conquista",
      "Warsaw",
      "Wellington",
      "Zurich"
    ]
  }))

  return app.save(collection)
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_477892449")

  // update field
  collection.fields.addAt(2, new Field({
    "hidden": false,
    "id": "select1788359516",
    "maxSelect": 1,
    "name": "cidade",
    "presentable": false,
    "required": false,
    "system": false,
    "type": "select",
    "values": [
      "Alagoinhas",
      "Americana",
      "Amsterdam",
      "Anapolis",
      "Ankara",
      "Aparecida de Goiania",
      "Aracaju",
      "Arapiraca",
      "Araraquara",
      "Araras",
      "Araucaria",
      "Asuncion",
      "Athens",
      "Auckland",
      "Bangkok",
      "Barcelona",
      "Beijing",
      "Belem",
      "Belo Horizonte",
      "Berlin",
      "Boa Vista",
      "Bogota",
      "Botucatu",
      "Brasilia",
      "Brussels",
      "Budapest",
      "Buenos Aires",
      "Cachoeiro de Itapemirim",
      "Cairo",
      "Campina Grande",
      "Campinas",
      "Campo Grande",
      "Campo Largo",
      "Cape Town",
      "Caracas",
      "Caruaru",
      "Cascavel",
      "Caucaia",
      "Caxias do Sul",
      "Chicago",
      "Contagem",
      "Copenhagen",
      "Criciuma",
      "Cuiaba",
      "Curitiba",
      "Delhi",
      "Denver",
      "Diadema",
      "Dubai",
      "Dublin",
      "Duque de Caxias",
      "Eunapolis",
      "Feira de Santana",
      "Florianopolis",
      "Fortaleza",
      "Foz do Iguacu",
      "Franca",
      "Frankfurt",
      "Goiania",
      "Governador Valadares",
      "Guarulhos",
      "Guayaquil",
      "Helsinki",
      "Hong Kong",
      "Houston",
      "Ilheus",
      "Imperatriz",
      "Istanbul",
      "Itabuna",
      "Itajai",
      "Itapetininga",
      "Itaquaquecetuba",
      "Jakarta",
      "Jerusalem",
      "Joao Pessoa",
      "Johannesburg",
      "Joinville",
      "Juazeiro do Norte",
      "Jundiai",
      "Juiz de Fora",
      "Kuala Lumpur",
      "La Paz",
      "Lagos",
      "Lima",
      "Lisbon",
      "London",
      "Londrina",
      "Los Angeles",
      "Luziania",
      "Macapa",
      "Maceio",
      "Madrid",
      "Manaus",
      "Manila",
      "Marilia",
      "Maua",
      "Melbourne",
      "Mexico City",
      "Miami",
      "Milan",
      "Mogi das Cruzes",
      "Mogi Guacu",
      "Montes Claros",
      "Montevideo",
      "Montreal",
      "Moscow",
      "Mossoro",
      "Mumbai",
      "Munich",
      "Nairobi",
      "Natal",
      "New York",
      "Niteroi",
      "Nova Friburgo",
      "Nova Iguacu",
      "Novo Hamburgo",
      "Olinda",
      "Oslo",
      "Osasco",
      "Ottawa",
      "Palmas",
      "Panama City",
      "Paramaribo",
      "Parauapebas",
      "Paris",
      "Passo Fundo",
      "Paulista",
      "Petropolis",
      "Piracicaba",
      "Porto Alegre",
      "Porto Velho",
      "Prague",
      "Presidente Prudente",
      "Quito",
      "Recife",
      "Ribeirao Preto",
      "Rio Branco",
      "Rio de Janeiro",
      "Rome",
      "Rondonopolis",
      "Salvador",
      "Santa Maria",
      "Santarem",
      "Santiago",
      "Santo Andre",
      "Santos",
      "Sao Bernardo do Campo",
      "Sao Carlos",
      "Sao Goncalo",
      "Sao Jose do Rio Preto",
      "Sao Jose dos Campos",
      "Sao Luis",
      "Sao Paulo",
      "Sao Vicente",
      "Seattle",
      "Seoul",
      "Singapore",
      "Sorocaba",
      "Stockholm",
      "Sumare",
      "Sydney",
      "Taipei",
      "Taubate",
      "Tehran",
      "Tel Aviv",
      "Teresina",
      "Tokyo",
      "Toronto",
      "Uberaba",
      "Uberlandia",
      "Urucu",
      "Vancouver",
      "Varzea Grande",
      "Vienna",
      "Vitoria",
      "Vitoria da Conquista",
      "Warsaw",
      "Wellington",
      "Zurich"
    ]
  }))

  return app.save(collection)
})
